### ISSUE TITLE
Bump version and cut a release

### ISSUE THREAD

**Issue by mjgiarlo** [Vasfed/flot-rails#15]
Can you bump the version to 0.0.7 and release the new version to rubygems.org? Alternatively, I'm happy to help if you want to grant me access to this repo and the gem. Thanks!

**Comment by mjgiarlo** [comment]
Here's why i want a new release: https://dependencyci.com/github/projecthydra/sufia/builds/2

**Comment by Vasfed** [comment]
Released 0.0.7

**Comment by mjgiarlo** [comment]
Thanks, @Vasfed!
